services:
  - type: web
    name: kestrel-weather-dashboard
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: AMBIENT_APPLICATION_KEY
        value: 953749d40bc84f48bdbabc1c57298546a0e6e53bc72a4a95bd0e938a97bf1156
      - key: AMBIENT_API_KEY
        value: d925fc2e121542dc9f231435cc44a8607c7eb604c92544de8edfca9f07f1c406
      - key: AMBIENT_DEVICE_MAC
        value: ""
      - key: NODE_VERSION
        value: "20"
